import React from 'react';

interface DownloadFormats {
  type: 'txt' | 'md' | 'json' | 'csv' | 'html';
}

/**
 * Download summary in TXT format
 */
export function downloadAsText(summary: string, fileName: string): void {
  const element = document.createElement('a');
  const file = new Blob([summary], { type: 'text/plain' });
  element.href = URL.createObjectURL(file);
  element.download = `${fileName.replace('.pdf', '')}_summary.txt`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

/**
 * Download summary in Markdown format
 */
export function downloadAsMarkdown(summary: string, fileName: string): void {
  const mdContent = `# Summary: ${fileName.replace('.pdf', '')}\n\n${summary}\n\n---\n*Generated by AI Research Paper Summarizer*`;
  const element = document.createElement('a');
  const file = new Blob([mdContent], { type: 'text/markdown' });
  element.href = URL.createObjectURL(file);
  element.download = `${fileName.replace('.pdf', '')}_summary.md`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

/**
 * Download summary in JSON format
 */
export function downloadAsJSON(summary: string, fileName: string): void {
  const jsonData = {
    fileName: fileName,
    timestamp: new Date().toISOString(),
    summary: summary,
    sections: summary.split('\n\n').map((section, idx) => ({
      id: idx + 1,
      content: section.trim(),
    })),
  };
  const element = document.createElement('a');
  const file = new Blob([JSON.stringify(jsonData, null, 2)], { type: 'application/json' });
  element.href = URL.createObjectURL(file);
  element.download = `${fileName.replace('.pdf', '')}_summary.json`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

/**
 * Download summary in CSV format
 */
export function downloadAsCSV(summary: string, fileName: string): void {
  const sections = summary.split('\n\n').map((section, idx) => ({
    id: idx + 1,
    content: section.trim().replace(/"/g, '""'), // Escape quotes
  }));

  const csvHeader = 'SectionID,Content\n';
  const csvRows = sections.map((s) => `${s.id},"${s.content}"`).join('\n');
  const csvContent = csvHeader + csvRows;

  const element = document.createElement('a');
  const file = new Blob([csvContent], { type: 'text/csv' });
  element.href = URL.createObjectURL(file);
  element.download = `${fileName.replace('.pdf', '')}_summary.csv`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

/**
 * Download summary in HTML format
 */
export function downloadAsHTML(summary: string, fileName: string): void {
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${fileName}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 40px 20px;
      min-height: 100vh;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      background: white;
      border-radius: 12px;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
      padding: 40px;
    }
    h1 {
      color: #333;
      margin-bottom: 10px;
      font-size: 28px;
    }
    .file-info {
      color: #666;
      font-size: 14px;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 2px solid #f0f0f0;
    }
    .timestamp {
      color: #999;
      font-size: 12px;
      margin-top: 5px;
    }
    .section {
      margin-bottom: 25px;
      padding: 20px;
      background: #f9f9f9;
      border-left: 4px solid #667eea;
      border-radius: 6px;
      line-height: 1.8;
      color: #333;
    }
    .section p {
      margin-bottom: 10px;
    }
    .section p:last-child {
      margin-bottom: 0;
    }
    footer {
      text-align: center;
      color: #999;
      font-size: 12px;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #f0f0f0;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>📚 Paper Summary</h1>
    <div class="file-info">
      <strong>File:</strong> ${fileName}
      <div class="timestamp">Generated: ${new Date().toLocaleString()}</div>
    </div>
    ${summary
      .split('\n\n')
      .map(
        (section) =>
          `<div class="section">${section
            .split('\n')
            .map((line) => `<p>${line}</p>`)
            .join('')}</div>`
      )
      .join('')}
    <footer>Generated by AI Research Paper Summarizer</footer>
  </div>
</body>
</html>`;

  const element = document.createElement('a');
  const file = new Blob([htmlContent], { type: 'text/html' });
  element.href = URL.createObjectURL(file);
  element.download = `${fileName.replace('.pdf', '')}_summary.html`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

/**
 * Download multiple papers comparison in different formats
 */
export function downloadComparisonAsText(papers: { fileName: string; summary: string }[]): void {
  const content = papers
    .map((paper) => `\n${'='.repeat(60)}\n📄 ${paper.fileName}\n${'='.repeat(60)}\n\n${paper.summary}`)
    .join('\n\n');

  const element = document.createElement('a');
  const file = new Blob([content], { type: 'text/plain' });
  element.href = URL.createObjectURL(file);
  element.download = 'papers_comparison.txt';
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

export function downloadComparisonAsJSON(papers: { fileName: string; summary: string }[]): void {
  const jsonData = {
    timestamp: new Date().toISOString(),
    paperCount: papers.length,
    papers: papers.map((paper) => ({
      fileName: paper.fileName,
      summary: paper.summary,
      sections: paper.summary.split('\n\n').map((section, idx) => ({
        id: idx + 1,
        content: section.trim(),
      })),
    })),
  };

  const element = document.createElement('a');
  const file = new Blob([JSON.stringify(jsonData, null, 2)], { type: 'application/json' });
  element.href = URL.createObjectURL(file);
  element.download = 'papers_comparison.json';
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

export function downloadComparisonAsHTML(papers: { fileName: string; summary: string }[]): void {
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Papers Comparison</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 40px 20px;
      min-height: 100vh;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
    }
    h1 {
      color: white;
      text-align: center;
      margin-bottom: 40px;
      font-size: 32px;
    }
    .papers-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
      gap: 25px;
    }
    .paper-card {
      background: white;
      border-radius: 12px;
      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
      overflow: hidden;
    }
    .paper-header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 20px;
      font-weight: bold;
      word-break: break-word;
    }
    .paper-content {
      padding: 25px;
      max-height: 600px;
      overflow-y: auto;
      line-height: 1.8;
      color: #333;
    }
    .section {
      margin-bottom: 20px;
      padding: 15px;
      background: #f9f9f9;
      border-left: 4px solid #667eea;
      border-radius: 4px;
    }
    .section p {
      margin-bottom: 8px;
    }
    .section p:last-child {
      margin-bottom: 0;
    }
    footer {
      text-align: center;
      color: white;
      padding: 40px 20px;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <h1>📊 Papers Comparison</h1>
  <div class="container">
    <div class="papers-grid">
      ${papers
        .map(
          (paper) =>
            `<div class="paper-card">
        <div class="paper-header">${paper.fileName}</div>
        <div class="paper-content">
          ${paper.summary
            .split('\n\n')
            .map(
              (section) =>
                `<div class="section">${section
                  .split('\n')
                  .map((line) => `<p>${line}</p>`)
                  .join('')}</div>`
            )
            .join('')}
        </div>
      </div>`
        )
        .join('')}
    </div>
  </div>
  <footer>Generated by AI Research Paper Summarizer on ${new Date().toLocaleString()}</footer>
</body>
</html>`;

  const element = document.createElement('a');
  const file = new Blob([htmlContent], { type: 'text/html' });
  element.href = URL.createObjectURL(file);
  element.download = 'papers_comparison.html';
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}
